Api/Views/Shared/Components/Navigation/NavigationViewComponent.cs
using Data.Dto_s.User;
using Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Service.Services;

namespace Api.Models
{
    public class NavigationViewComponent : ViewComponent
    {
        private UserService _userService;
        private AccountService _accountService;

        public NavigationViewComponent(UserService userService, AccountService accountService)
        {
            _userService = userService;
            _accountService = accountService;
        }

        public IViewComponentResult Invoke()
        {
            string userEmail = HttpContext.User.Identity.Name;
            NavUserDto? user = null;
            if (!string.IsNullOrEmpty(userEmail))
            {
                Account account = _accountService.GetByEmail(userEmail);
                user = _userService.GetNavUserDto(account.Id);
            }

            return View(user);
        }
    }
}

Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Link</title>

    <!-- Styles -->
    <link rel="stylesheet" href="~/styles/main/main.css">
    <link rel="stylesheet" href="~/styles/messages/messages.css">
    <script defer src="~/lib/jquery/dist/jquery.min.js"></script>
    <script defer src="~/lib/main.js"></script>
</head>
<body>
    <div id="root">
        <nav>
            @await Component.InvokeAsync("Navigation")
        </nav>

        <div class="content">
            @RenderBody()
        </div>

        <div id="footer">
            <p>
                &copy; 2022 - Link - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </p>
        </div>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>